## 루프는 느리다
* NumPy는 여러 종류의 연산에 대해 정적 타입 체계를 가진 컴파일된 루틴에 편리한 인터페이스 제공 = 벡터화 연산
* 유니버셜함수(UFunc)를 통한 벡터화를 이용한 연산은 파이썬 루프를 통해 구현되는 연산보다 대부분 더 효율적, 특히 배열의 크기가 커질수록 그 차이가 확연

## 1. 배열 산술 연산

In [1]:
import numpy as np
x = np.arange(4)
print(x)

[0 1 2 3]


### 1.1 기본 연산자와 스칼라
* \+ : 더하기
* \- : 빼기, 음수
* \* : 곱하기
* ** : 제곱
* / : 나누기
* // : 몫
* % : 나머지

In [2]:
x+5 # +,-,*,/,//, **. %

array([5, 6, 7, 8])

In [3]:
x**2

array([0, 1, 4, 9], dtype=int32)

In [4]:
x%2

array([0, 1, 0, 1], dtype=int32)

In [5]:
-x

array([ 0, -1, -2, -3])

### 1.2 배열 간 연산

In [6]:
np.random.seed(1)
x = np.random.randint(10, size=(2,3))
y = np.random.randint(10, size=(2,3))

print(x);print(y)

[[5 8 9]
 [5 0 0]]
[[1 7 6]
 [9 2 4]]


In [7]:
x+y

array([[ 6, 15, 15],
       [14,  2,  4]])

In [8]:
x*y

array([[ 5, 56, 54],
       [45,  0,  0]])

### 1.3 브로드캐스팅

+ 대응되는 길이의 배열로 만들어 크기를 같게 한 후 연산을 실행

![broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [9]:
x = np.ones(6).reshape(2,3)
z = np.arange(3)
w = np.arange(2)[:,np.newaxis] # 열벡터 생성
print(x);print(z); print(w)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[0]
 [1]]


In [10]:
x + z

array([[1., 2., 3.],
       [1., 2., 3.]])

In [11]:
x + w

array([[1., 1., 1.],
       [2., 2., 2.]])

In [12]:
z + w

array([[0, 1, 2],
       [1, 2, 3]])

---
## 2 배열의 주요 함수

In [3]:
x = np.random.random(100000)

### 2.1 요소의 합

In [4]:
np.sum(x) 

49936.889271960434

#### 속도비교

In [5]:
%timeit np.sum(x)
%timeit sum(x)

37 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
11.4 ms ± 93.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 다차원 배열의 합

In [6]:
M = np.random.random((3,4))
print(M)

[[0.91342591 0.72709322 0.79102151 0.33370693]
 [0.13963619 0.33585125 0.1991268  0.13127718]
 [0.51209589 0.71494835 0.24297154 0.12278782]]


In [7]:
M.sum()

5.163942595699985

In [8]:
np.sum(M) ## 추천

5.163942595699985

#### 열 방향

In [21]:
M.sum(axis=0) # 첫번째 차원을 축소 열축소

array([1.91898802, 0.94557324, 2.09799565, 1.66828223])

In [22]:
np.sum(M, axis=0)

array([1.91898802, 0.94557324, 2.09799565, 1.66828223])

#### 행 방향

In [23]:
M.sum(axis=1) # 두번째 차원을 축소 열방향으로 축소 행단위로 합계

array([1.56918421, 1.93261604, 3.12903888])

In [24]:
np.sum(M, axis=1)

array([1.56918421, 1.93261604, 3.12903888])

### 2.2 요소의 평균, 분산, 표준편차

In [30]:
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


#### 평균

In [26]:
np.mean(x)

5.5

#### 중앙값

In [31]:
np.median(x)

5.5

#### 분위수

In [32]:
np.percentile(x,[25,50,75])

array([3.25, 5.5 , 7.75])

#### 분산

In [33]:
np.var(x) # (x - avg(x))**2/n

8.25

#### 표준편차

In [34]:
np.std(x)

2.8722813232690143

### 2.3 요소의 최대 최소

#### 값

In [36]:
x.min() #최소값
np.min(x)

1

In [37]:
x.max() #최대값
np.max(x)

10

#### 위치

In [38]:
x.argmin() #최소값의 위치

0

In [39]:
x.argmax() #최대값의 위치

9

### 2.4 참/거짓 요소 확인

In [40]:
x = np.repeat([True, False], [5,1])
print(x)

[ True  True  True  True  True False]


#### 요소 중 참이 있는지 확인

In [41]:
np.any(x)

True

#### 모든 요소가 참인지 확인

In [42]:
np.all(x)

False

#### 요소 중 참의 갯수 확인

In [43]:
x.sum()

5

## 3. 그 외 함수

### 3.1 절대값

In [ ]:
x=np.array([-2,-1,0,1,2,])
print(x)

In [ ]:
abs(x)

### 3.2 지수

In [44]:
x = np.arange(1,5)
print(x)

[1 2 3 4]


In [45]:
np.exp(x) # e**x

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [46]:
np.exp2(x) # 2**x

array([ 2.,  4.,  8., 16.])

In [47]:
np.power(3,x) # 3**x

array([ 3,  9, 27, 81], dtype=int32)

### 3.3 로그

In [48]:
np.log(x) # log_e

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [49]:
np.log2(x) # log_2

array([0.       , 1.       , 1.5849625, 2.       ])

### 3.4 집계

In [51]:
print(x)

[1 2 3 4]


In [50]:
np.add.reduce(x) #누적 합

10

In [52]:
np.add.accumulate(x)  #누적 합 (과정 기록)

array([ 1,  3,  6, 10], dtype=int32)

In [53]:
np.multiply.reduce(x)  #누적 곱

24

In [54]:
np.multiply.accumulate(x)  #누적 곱 (과정 기록)

array([ 1,  2,  6, 24], dtype=int32)

### 3.5 외적과 내적

In [ ]:
np.multiply.outer(x,x) # 외적

In [ ]:
x.dot(x) # 내적

## 4. 정렬

In [55]:
x = np.array([2,1,4,3,5])
print(x)

[2 1 4 3 5]


In [56]:
np.sort(x) # 값 반환

array([1, 2, 3, 4, 5])

In [57]:
np.argsort(x) # 정렬된 값의 인덱스 반환

array([1, 0, 3, 2, 4], dtype=int64)

#### np.sort를 했다고 x의 값이 변경되진 않음

In [58]:
print(x) 

[2 1 4 3 5]


In [59]:
x.sort() # 정렬된 값으로 변경
print(x)

[1 2 3 4 5]
