In [1]:
import numpy as np

In [3]:
x = np.arange(1,100,2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [4]:
y = x.reshape(5,10)
y

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [10]:
y.ndim

2

In [11]:
y.shape

(5, 10)

In [12]:
y.size

50

In [13]:
x[len(x)-10:len(x)]

array([81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [14]:
x[::2]

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [15]:
x[::-2]

array([99, 95, 91, 87, 83, 79, 75, 71, 67, 63, 59, 55, 51, 47, 43, 39, 35,
       31, 27, 23, 19, 15, 11,  7,  3])

In [17]:
z = 7*8
z

56

In [22]:
w = np.tile([2,4,6,8,10],5)
w

array([ 2,  4,  6,  8, 10,  2,  4,  6,  8, 10,  2,  4,  6,  8, 10,  2,  4,
        6,  8, 10,  2,  4,  6,  8, 10])

In [24]:
k = np.concatenate([x,w])
k

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99,  2,
        4,  6,  8, 10,  2,  4,  6,  8, 10,  2,  4,  6,  8, 10,  2,  4,  6,
        8, 10,  2,  4,  6,  8, 10])

In [25]:
np.sum(k)

2650

In [26]:
np.mean(k)

35.333333333333336

In [27]:
np.median(k)

25.0

In [28]:
np.std(k)

31.436002007606216

In [34]:
k.max()
np.max(k)

99

In [35]:
k.min()
np.min(k)

1

In [36]:
k[k>np.mean(k)].size

32

In [38]:
k[k>np.mean(k)]

array([37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [47]:
k[(k > np.mean(k)) & (k < (np.mean(k) + np.std(k)))]

array([37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65])

In [55]:
np.sort(k)

array([ 1,  2,  2,  2,  2,  2,  3,  4,  4,  4,  4,  4,  5,  6,  6,  6,  6,
        6,  7,  8,  8,  8,  8,  8,  9, 10, 10, 10, 10, 10, 11, 13, 15, 17,
       19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51,
       53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85,
       87, 89, 91, 93, 95, 97, 99])

In [56]:
np.sort(k)[::-1]

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33,
       31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11, 10, 10, 10, 10, 10,  9,
        8,  8,  8,  8,  8,  7,  6,  6,  6,  6,  6,  5,  4,  4,  4,  4,  4,
        3,  2,  2,  2,  2,  2,  1])

In [59]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [60]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [62]:
np.repeat(np.arange(2,11,2),5)

array([ 2,  2,  2,  2,  2,  4,  4,  4,  4,  4,  6,  6,  6,  6,  6,  8,  8,
        8,  8,  8, 10, 10, 10, 10, 10])

In [63]:
np.tile(np.arange(2,11,2),5)

array([ 2,  4,  6,  8, 10,  2,  4,  6,  8, 10,  2,  4,  6,  8, 10,  2,  4,
        6,  8, 10,  2,  4,  6,  8, 10])